### ISSUE TITLE
Half-maximized window issues

### ISSUE THREAD

**Issue by Beanow** [pixel-saver/pixel-saver#135]
There are a few issues I noticed with half-maximized windows I thought I would aggregate into one issue. Feel free to edit my OP when new ones crop up.

- [ ] #16 The window min/max/close buttons aren't shown.
_Expected behavior is unclear._
- [ ] AppMenu label does not show window titles.
_Although there's only one, showing the focused window title makes sense to me._
- [ ] The right half initially does not fully "merge", only after un- and re-focusing.
_Window is only undecorated, [Dynamic top bar](https://extensions.gnome.org/extension/885/dynamic-top-bar/) does not update transparency either.
This does not happen on the left half._

![screenshot from 2017-07-10 18-23-54](https://user-images.githubusercontent.com/497556/28029005-c63767d0-659e-11e7-9370-8d450b56a215.png)

**Comment by fastcat** [comment]
Seems related to #80 ... kinda

**Comment by RalfJung** [comment]
> The window min/max/close buttons aren't shown.

Not just that -- if I change the focus from a half/maximized window to a "normal" window, and then use the min/max/close buttons, they seem to affect both windows. I had very mysterious side-effects from using this extension and half-maximized windows, making the extension unusable.

**Comment by bittner** [comment]
Related to #16 (maybe duplicate).

**Comment by keunes** [comment]
Thanks @tallero for taking over maintenance/development :)
I was just wondering: any particular reason for closing this issue? Is there a duplicate I should follow instead, or will/is this solved in a new version?

**Comment by tallero** [comment]
>Thanks @tallero for taking over maintenance/development :)
I was just wondering: any particular reason for closing this issue? Is there a duplicate I should follow instead, or will/is this solved in a new version?

About the first point, see [this](https://github.com/pixel-saver/pixel-saver/issues/16#issuecomment-260172584). As deadalnix, I think it is not good at all to have buttons displayed in positions that could be really far from the half-maximized window.

I think a feasible solution could be to add window controls in the no-more application menu, as was proposed when we [opposed](https://gitlab.gnome.org/GNOME/gnome-shell/issues/624) to app menu deprecation.

Actually a wrote an [extension](https://extensions.gnome.org/extension/1496/focused-window-indicator/) (<=3.30) that did add this functionality (and window transparency too).

I think it could be worth to wait because I heard it could be integrated in default gnome anyway.

The second point of the issue has been marked by OP.

About the third point I believe the issue has probably been solved by itself later at some point with a later PS or Shell version, since I never experienced it (this issue is from 2017).

Finally, I see from the screenshot that @Beanow is probably using dash to panel (and dynamic top bar) so I believe that in any case this should be solved by input from both sides.

Feel free to refer this issue in a new one on [dash-to-panel](https://github.com/home-sweet-gnome/dash-to-panel) repo, if it persists.
