### ISSUE TITLE
Project Still Active?

### ISSUE THREAD

**Issue by jcuenod** [pixel-saver/pixel-saver#159]
The last commit was 6 months ago (Sept 2017). I see that there are a number of unclosed issues and outstanding pull requests that date back to 2016.

Is this project still active?

I understand that a lot of work is involved in maintaining extensions with Gnome... I just think it would be good for the community to know if you consider this a dead project. Thanks.

**Comment by deadalnix** [comment]
Hi @jcuenod . The answer is yes and no. Sadly or happily I've become the lead maintainer of another open source software that has become very popular ( https://github.com/Bitcoin-ABC/bitcoin-abc ). I'm still using that extension myself. Time is really the issue here. If you would like to help, maybe we can create an org and have the dev happen there, which would remove the bottleneck on myself.

**Comment by jcuenod** [comment]
Well to be honest, I don't want to take over the project but it seems as though the folks at https://github.com/franglais125/no-title-bar/ are doing a pretty good job of forking and pushing on... Is it not worth consolidating effort/pointing people to that extension (even giving them @franglais125 ownership so that the PRs can be meaningfully considered though a rebase may be required).
I don't know, I feel like it would be beneficial not to have two projects.

**Comment by franglais125** [comment]
@jcuenod @deadalnix I'm all for unification, rather than forking, if you'd like that. (Co-)maintaining this project is fine with me as well, if need be! Cheers

**Comment by keunes** [comment]
Any update on this? While I don't have any development skills myself (I only do translations) and am of no help here, I'm a new and enthusiastic user of this extension. I just did a fresh install of Ubuntu 18.04 and missed the vertical spacial efficiency of Unity, and am happy to have found this extension. Would be a pity if it wouldn't be updated/supported anymore.

**Comment by tallero** [comment]
The project is active.

**Comment by JensTimmerman** [comment]
@tallero thank you for taking over this project!
I have removed my fork and inactivated the versions of the extension I uploaded to extensions.gnome.org

**Comment by tallero** [comment]
@JensTimmerman Wow, that was fast!
Your patch was awesome, it is amazing to have pixel saver again; I had sincerely lost hope since I became heavily dependent on Synergy/barrier (it was breaking it around april and I didn't think to know how to easily solve it).

The comment was maybe ahead of the times, since I still can't update the extension on the website. I just discovered I [requested](https://mail.gnome.org/archives/gnome-shell-extensions-list/2019-August/msg00000.html) the trasfer on [the wrong mailing list](https://mail.gnome.org/archives/gnome-shell-list/2016-March/msg00030.html).

**Comment by JensTimmerman** [comment]
The latest patches broke on latest gnome, gnome would hang after comming back from locked screen so I had to spend some time on fixing it, and I believe it's better to combine efforts centrally ;)
However, if you think you have a working release that could be pushed to extensions.gnome.org tag it and give me the tag, I can push a few release to the pixel-saver-fork if you like, but I'd rather follow the official procedures and get you control over the gnome extensions official version instead of telling people to use random forks.

**Comment by tallero** [comment]
>The latest patches broke on latest gnome, gnome would hang after comming back from locked screen so I had to spend some time on fixing it, and I believe it's better to combine efforts centrally ;)

Do you mean on 3.34? Because I am not experiencing this; of the [lock screen issues reported](https://github.com/pixel-saver/pixel-saver/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+lock) I can reproduce only the third in the list.

>However, if you think you have a working release that could be pushed to extensions.gnome.org tag it and give me the tag, I can push a few release to the pixel-saver-fork if you like, but I'd rather follow the official procedures and get you control over the gnome extensions official version instead of telling people to use random forks.

No, It is just that I think that it could take a while, so having an updated version already published could be better for users to avoid letting them disperse.

>To be clear, I never made any patches myself, I never have written a single line of code for pixel-saver, all I did was combine some open pull requests on this repo into my fork of the repo ;)

You are right, I merged from @Jimver. Well, your involvement is cool the same!
