### ISSUE TITLE
Destroy fail on suspend

### ISSUE THREAD

**Issue by regfaker** [pixel-saver/pixel-saver#196]
Pixel Saver v1.10+git20180804-d97c6e4-1, Gnome 3.30.2
Debian buster, 4.19.0-2-amd64 #1 SMP Debian 4.19.16-1 (2019-01-17) x86_64 GNU/Linux
pixel-saver fails when on suspend, syslog excerpt:
[syslog-pixelsaver-suspend.txt](https://github.com/deadalnix/pixel-saver/files/2997999/syslog-pixelsaver-suspend.txt)
causing gnome-shell segfault thus Unrecoverable failure (see log) so after resume all started applications are gone.
Please investigate this. Thank you

**Comment by vthuongt** [comment]
I think I observe the same problem for Ubuntu:
an excerpt from `journalctl`:

> Mai 07 09:09:07 GPUPC gnome-shell[2476]: g_signal_handler_disconnect: assertion 'handler_id > 0' failed
Mai 07 09:09:07 GPUPC gnome-shell[2476]: Object Shell.GenericContainer (0x56442f53ad00), has been already deallocated - impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() v
Mai 07 09:09:07 GPUPC org.gnome.Shell.desktop[2476]: == Stack trace for context 0x56442e63f330 ==
Mai 07 09:09:07 GPUPC org.gnome.Shell.desktop[2476]: #0 0x56442ead5848 i   resource:///org/gnome/gjs/modules/overrides/GObject.js:460 (0x7ffa882c4890 @ 25)
Mai 07 09:09:07 GPUPC org.gnome.Shell.desktop[2476]: #1 0x56442ead57c8 i   /home/userxyz/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/app_menu.js:210 (0x7ffa640e56f8 @ 97)
Mai 07 09:09:07 GPUPC org.gnome.Shell.desktop[2476]: #2 0x56442ead5750 i   /home/userxyz/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/extension.js:65 (0x7ffa640dd340 @ 12)
Mai 07 09:09:07 GPUPC org.gnome.Shell.desktop[2476]: #3 0x56442ead5690 i   resource:///org/gnome/shell/ui/extensionSystem.js:83 (0x7ffa7c6592b8 @ 441)
Mai 07 09:09:07 GPUPC org.gnome.Shell.desktop[2476]: #4 0x56442ead5610 i   resource:///org/gnome/shell/ui/extensionSystem.js:354 (0x7ffa7c659d58 @ 13)
Mai 07 09:09:07 GPUPC org.gnome.Shell.desktop[2476]: #5 0x7ffefb8c15d0 b   self-hosted:251 (0x7ffa882c4ab0 @ 223)
Mai 07 09:09:07 GPUPC org.gnome.Shell.desktop[2476]: #6 0x56442ead5590 i   resource:///org/gnome/shell/ui/extensionSystem.js:353 (0x7ffa7c659cd0 @ 64)
Mai 07 09:09:07 GPUPC org.gnome.Shell.desktop[2476]: #7 0x56442ead5510 i   resource:///org/gnome/shell/ui/extensionSystem.js:371 (0x7ffa7c659de0 @ 87)
Mai 07 09:09:07 GPUPC org.gnome.Shell.desktop[2476]: #8 0x7ffefb8c23c0 I   resource:///org/gnome/gjs/modules/signals.js:128 (0x7ffa882d2230 @ 386)
Mai 07 09:09:07 GPUPC org.gnome.Shell.desktop[2476]: #9 0x7ffefb8c2b60 b   resource:///org/gnome/shell/ui/sessionMode.js:205 (0x7ffa7c36bef0 @ 254)
Mai 07 09:09:07 GPUPC org.gnome.Shell.desktop[2476]: #10 0x7ffefb8c3840 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7ffa882b5de0 @ 71)
Mai 07 09:09:07 GPUPC org.gnome.Shell.desktop[2476]: #11 0x56442ead53d0 i   resource:///org/gnome/shell/ui/sessionMode.js:167 (0x7ffa7c36bcd0 @ 40)
Mai 07 09:09:07 GPUPC org.gnome.Shell.desktop[2476]: #12 0x7ffefb8c4420 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7ffa882b5de0 @ 71)
Mai 07 09:09:07 GPUPC org.gnome.Shell.desktop[2476]: #13 0x56442ead5338 i   resource:///org/gnome/shell/ui/screenShield.js:1041 (0x7ffa7c3509a0 @ 421)
Mai 07 09:09:07 GPUPC org.gnome.Shell.desktop[2476]: #14 0x7ffefb8c5000 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7ffa882b5de0 @ 71)
Mai 07 09:09:07 GPUPC org.gnome.Shell.desktop[2476]: #15 0x56442ead5290 i   resource:///org/gnome/shell/ui/screenShield.js:1285 (0x7ffa7c3524d8 @ 223)
Mai 07 09:09:07 GPUPC org.gnome.Shell.desktop[2476]: #16 0x7ffefb8c5be0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7ffa882b5de0 @ 71)
Mai 07 09:09:07 GPUPC org.gnome.Shell.desktop[2476]: #17 0x56442ead51e0 i   resource:///org/gnome/shell/ui/screenShield.js:1331 (0x7ffa7c352560 @ 391)
Mai 07 09:09:07 GPUPC org.gnome.Shell.desktop[2476]: #18 0x7ffefb8c67c0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7ffa882b5de0 @ 71)
Mai 07 09:09:07 GPUPC org.gnome.Shell.desktop[2476]: #19 0x56442ead5158 i   resource:///org/gnome/shell/ui/screenShield.js:734 (0x7ffa7c34ef78 @ 57)
Mai 07 09:09:07 GPUPC systemd[1]: Started resolvconf-pull-resolved.service.
Mai 07 09:09:07 GPUPC org.gnome.Shell.desktop[2476]: #20 0x7ffefb8c73b0 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7ffa882b5de0 @ 71)
Mai 07 09:09:07 GPUPC org.gnome.Shell.desktop[2476]: #21 0x7ffefb8c7480 b   self-hosted:918 (0x7ffa882f12b8 @ 394)
Mai 07 09:09:07 GPUPC org.gnome.Shell.desktop[2476]: #22 0x7ffefb8c7510 I   resource:///org/gnome/gjs/modules/signals.js:128 (0x7ffa882d2230 @ 386)
Mai 07 09:09:07 GPUPC org.gnome.Shell.desktop[2476]: #23 0x56442ead50c0 i   resource:///org/gnome/shell/misc/loginManager.js:186 (0x7ffa7c612230 @ 92)
Mai 07 09:09:07 GPUPC org.gnome.Shell.desktop[2476]: #24 0x7ffefb8c8110 I   resource:///org/gnome/gjs/modules/_legacy.js:82 (0x7ffa882b5de0 @ 71)
Mai 07 09:09:07 GPUPC org.gnome.Shell.desktop[2476]: #25 0x7ffefb8c81f0 b   self-hosted:920 (0x7ffa882f12b8 @ 428)
Mai 07 09:09:07 GPUPC org.gnome.Shell.desktop[2476]: #26 0x7ffefb8c8280 I   resource:///org/gnome/gjs/modules/signals.js:128 (0x7ffa882d2230 @ 386)
Mai 07 09:09:07 GPUPC org.gnome.Shell.desktop[2476]: #27 0x56442ead5020 i   resource:///org/gnome/gjs/modules/overrides/Gio.js:117 (0x7ffa882e0ab0 @ 39)

System info:
GNOME Shell 3.28.3
Ubuntu 18.04.2 LTS with Kernel  4.15.0-43-generic 
pixel-saver was installed via gnome-shell extensions website and is up to date

**Comment by tallero** [comment]
I can't reproduce the bug in 3.32.2 on archlinux. Suspend is correctly working for me.
