### ISSUE TITLE
edge tiling does not working after pixel-saver is enabled

### ISSUE THREAD

**Issue by Tanglifei** [pixel-saver/pixel-saver#230]
Hi 
I am using Ubuntu 20.04 with GNOME Shell 3.36.9
Pixel-saver works great expect the edge tiling does not working when pixel-saver is enabled.
Edge tiling is enabled from gnome-tweak, which works immediately after pixel-saver is disabled. 
Any suggestion to make pixel saver works together with edge tiling 
Many thanks

**Comment by tallero** [comment]
As far as I know it shouldn't be possible for Pixel Saver to interfere with mutter edge tiling in ayn way, and I've used edge tiling with in GNOME Shell  during the `3.36`-`3.38` cycle without trouble.

I suspect the problem is on your side; if not, try switching pixel saver version to the first one compatible with GNOME 3.36 and/or upgrading to latest version.
